// Package assets serves deterministic console-shell CSS and runtime JavaScript.
package assets

import (
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"net/http"
	"strings"
)

const defaultPrefix = "/consoleshell/assets/"

var (
	//go:embed shell.css
	stylesheet []byte
	//go:embed shell.js
	script            []byte
	stylesheetVersion = version(stylesheet)
	scriptVersion     = version(script)
)

// Handler serves the embedded console-shell assets. URLs generated by
// StylesheetURL and ScriptURL receive immutable caching; unversioned requests
// remain revalidatable, and stale version tokens are rejected.
func Handler(prefixes ...string) http.Handler {
	prefix := defaultPrefix
	if len(prefixes) > 0 {
		prefix = normalizePrefix(prefixes[0])
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Content-Type-Options", "nosniff")
		var body []byte
		var contentType, currentVersion string
		switch r.URL.Path {
		case prefix + "shell.css":
			body, contentType, currentVersion = stylesheet, "text/css; charset=utf-8", stylesheetVersion
		case prefix + "shell.js":
			body, contentType, currentVersion = script, "text/javascript; charset=utf-8", scriptVersion
		default:
			http.NotFound(w, r)
			return
		}

		requestedVersion := r.URL.Query().Get("v")
		if requestedVersion != "" && requestedVersion != currentVersion {
			http.NotFound(w, r)
			return
		}
		if requestedVersion == currentVersion {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		} else {
			w.Header().Set("Cache-Control", "public, max-age=0, must-revalidate")
		}
		w.Header().Set("Content-Type", contentType)
		_, _ = w.Write(body)
	})
}

// StylesheetURL returns the content-versioned URL for the embedded shell CSS.
func StylesheetURL(prefix string) string {
	return normalizePrefix(prefix) + "shell.css?v=" + stylesheetVersion
}

// ScriptURL returns the content-versioned URL for the embedded shell runtime.
func ScriptURL(prefix string) string { return normalizePrefix(prefix) + "shell.js?v=" + scriptVersion }
func version(b []byte) string        { s := sha256.Sum256(b); return hex.EncodeToString(s[:6]) }
func normalizePrefix(prefix string) string {
	if prefix == "" {
		return defaultPrefix
	}
	return strings.TrimSuffix(prefix, "/") + "/"
}
